# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuoteForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'', max_length=40)),
                ('last_name', models.CharField(default=b'', max_length=40)),
                ('email1', models.CharField(default=b'', max_length=255)),
                ('email2', models.CharField(default=b'', max_length=255)),
                ('location', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('company', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default=b'', max_length=12, null=True)),
                ('existing_client', models.BooleanField()),
                ('referral', models.CharField(blank=True, choices=[(b'WEB', b'Web Search'), (b'FB', b'Facebook'), (b'DD', b'DoneDeal'), (b'GT', b'GumTree'), (b'WOM', b'Word of Mouth'), (b'O', b'Other')], max_length=1, null=True)),
            ],
        ),
    ]
