# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customquoteform',
            name='phone',
        ),
        migrations.AddField(
            model_name='customquoteform',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customquoteform',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
