# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170517_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomQuoteForm',
            new_name='CustomQuote',
        ),
    ]
