# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170517_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquote',
            name='new_client',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
