# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_customquote_new_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquote',
            name='referral',
            field=models.CharField(blank=True, choices=[(b'WEB', b'Web Search'), (b'FB', b'Facebook'), (b'DD', b'DoneDeal'), (b'GT', b'GumTree'), (b'WOM', b'Word of Mouth'), (b'O', b'Other')], max_length=3, null=True),
        ),
    ]
