# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20170517_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquote',
            name='audio_minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customquote',
            name='description',
            field=models.TextField(default=b''),
        ),
    ]
