# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20170517_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default=b'', null=True),
        ),
    ]
