# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20170517_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquote',
            name='audio_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
