# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadFiles',
        ),
    ]
