# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170518_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='video_files',
        ),
    ]
