# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20170519_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
