# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_uploadfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to='client_files/%Y/%m/%d'),
        ),
    ]
