# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20170519_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='file_length',
            field=models.CharField(default='', max_length=255),
        ),
    ]
