# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_uploadfiles_file_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='client_files/%Y/%m/%d'),
        ),
    ]
