# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20170520_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file_length',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
