# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0012_uploadfiles_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='file_length',
            new_name='file_length_mins',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='file_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
