# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_auto_20170520_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('InProgress', 'In Progress'), ('Done', 'Done')], default='Processing', max_length=5),
        ),
    ]
