# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_auto_20170520_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptdetails',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Legal', 'Legal'), ('Medical', 'Medical'), ('Personal', 'Personal'), ('Academic', 'Academic')], default='General', max_length=8),
        ),
    ]
