# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0019_auto_20170520_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptdetails',
            name='num_speakers',
            field=models.CharField(choices=[(1, '1 Speaker'), (2, '2 Speakers'), (3, '3 Speakers'), (4, '4+ Speakers'), (10, '10+ Speakers')], default='1 Speaker', max_length=2),
        ),
    ]
