# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_auto_20170520_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptdetails',
            name='num_speakers',
            field=models.CharField(choices=[('1', '1 Speaker'), ('2', '2 Speakers'), ('3', '3 Speakers'), ('4', '4+ Speakers'), ('10', '10+ Speakers')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='transcriptdetails',
            name='tat',
            field=models.CharField(choices=[('24', '24 Hour'), ('48', '48 Hour'), ('Standard', 'Standard (Up To 4 Days)')], default='Standard', max_length=8),
        ),
    ]
