# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_transcriptdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptdetails',
            name='file_upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.UploadFiles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='upload.TranscriptDetails'),
            preserve_default=False,
        ),
    ]
