# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0024_remove_uploadfiles_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptdetails',
            name='file_upload',
        ),
    ]
