# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0026_auto_20170520_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptdetails',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
