# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0028_auto_20170522_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptdetails',
            name='upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.UploadFiles'),
            preserve_default=False,
        ),
    ]
