# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0029_transcriptdetails_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptdetails',
            name='upload',
        ),
        migrations.AddField(
            model_name='transcriptdetails',
            name='status',
            field=models.CharField(choices=[(b'Processing', b'Processing'), (b'InProgress', b'In Progress'), (b'Done', b'Done')], default='Processing', max_length=5),
        ),
    ]
