# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_auto_20170522_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload.TranscriptDetails'),
            preserve_default=False,
        ),
    ]
