# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0031_uploadfiles_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='details',
        ),
    ]
