# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0032_remove_uploadfiles_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='transcript_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='upload.TranscriptDetails'),
        ),
    ]
