# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0034_auto_20170529_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptdetails',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
