# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 00:13
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0038_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
