# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-05 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0039_auto_20170605_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='comment',
        ),
    ]
