# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-12 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0042_auto_20180512_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptdetails',
            name='status',
            field=models.CharField(choices=[(b'Processing', b'Processing'), (b'InProgress', b'In Progress'), (b'Done', b'Done')], default='Processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='status',
            field=models.CharField(choices=[(b'Processing', b'Processing'), (b'InProgress', b'In Progress'), (b'Done', b'Done')], default='Processing', max_length=100),
        ),
    ]
